export const GET_ACCELERATION_DATA_SUCCESS = 'GET_ACCELERATION_DATA_SUCCESS';
export const GET_ACCELERATION_DATA_FAILURE = 'GET_ACCELERATION_DATA_FAILURE';
export const GET_FFT_DATA_SUCCESS = 'GET_FFT_DATA_SUCCESS';
export const GET_FFT_DATA_FAILURE = 'GET_FFT_DATA_FAILURE';
